[log.d]
path = './log'

[conf.d]
path = './config'

[supervisor]
bin = "supervisord"
args = "-c"
conf = "./config/supervisor.ini"

[privoxy]
path = './bin/privoxy'
bin = "privoxy.exe"
conf = './config/'

[ss-rust]
path = './bin/ss-rust'
bin = "sslocal.exe"
conf = './config/'
