[log.d]
path = './log'

[conf.d]
path = './conf'

[supervisor]
path = './'
bin = "supervisord"
args = "-c"
conf = "./conf/supervisor.ini"

[privoxy]
path = './bin/privoxy'
bin = "privoxy.exe"

[ss-rust]
path = './bin/ss-rust'
bin = "sslocal.exe"
